import { IReadonlyTheme } from '@microsoft/sp-component-base';

export const themeVariant: IReadonlyTheme = {
  palette: {
    themeDarker: '#123f6b',
    themeDark: '#185591',
    themeDarkAlt: '#1c65ac',
    themePrimary: '#2270bf',
    themeSecondary: '#367ec7',
    themeTertiary: '#6ea3d9',
    themeLight: '#b2ceec',
    themeLighter: '#d4e5f5',
    themeLighterAlt: '#f4f8fc',
    black: '#000000',
    blackTranslucent40: 'rgba(0,0,0,.4)',
    neutralDark: '#131a1e',
    neutralPrimary: '#293339',
    neutralPrimaryAlt: '#605e5c',
    neutralSecondary: '#455560',
    neutralSecondaryAlt: '#8a8886',
    neutralTertiary: '#80939f',
    neutralTertiaryAlt: '#a9b4bb',
    neutralQuaternary: '#b4b8bc',
    neutralQuaternaryAlt: '#c7d1d8',
    neutralLight: '#d7e0e6',
    neutralLighter: '#ecf0f4',
    neutralLighterAlt: '#f1f5f8',
    accent: '#569fae',
    white: '#ffffff',
    whiteTranslucent40: 'rgba(255, 255, 255, 0.40)',
    yellow: '#ffb900',
    yellowLight: '#fff100',
    orange: '#d83b01',
    orangeLight: '#ea4300',
    orangeLighter: '#ff8c00',
    redDark: '#a4262c',
    red: '#e81123',
    magentaDark: '#5c005c',
    magenta: '#b4009e',
    magentaLight: '#e3008c',
    purpleDark: '#32145a',
    purple: '#5c2d91',
    purpleLight: '#b4a0ff',
    blueDark: '#002050',
    blueMid: '#00188f',
    blue: '#0078d4',
    blueLight: '#00bcf2',
    tealDark: '#004b50',
    teal: '#008272',
    tealLight: '#00b294',
    greenDark: '#004b1c',
    green: '#107c10',
    greenLight: '#bad80a'
  },
  fonts: {
    tiny: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '10px',
      fontWeight: 400
    },
    xSmall: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '10px',
      fontWeight: 400
    },
    small: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '12px',
      fontWeight: 400
    },
    smallPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '12px',
      fontWeight: 400
    },
    medium: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '14px',
      fontWeight: 400
    },
    mediumPlus: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '16px',
      fontWeight: 400
    },
    large: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '18px',
      fontWeight: 400
    },
    xLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '20px',
      fontWeight: 600
    },
    xxLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '28px',
      fontWeight: 600
    },
    superLarge: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '42px',
      fontWeight: 600
    },
    mega: {
      fontFamily:
        "'Segoe UI', 'Segoe UI Web (West European)', 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Roboto', 'Helvetica Neue', sans-serif",
      MozOsxFontSmoothing: 'grayscale',
      WebkitFontSmoothing: 'antialiased',
      fontSize: '68px',
      fontWeight: 600
    }
  },
  semanticColors: {
    bodyBackground: '#ffffff',
    bodyStandoutBackground: '#f1f5f8',
    bodyFrameBackground: '#ffffff',
    bodyFrameDivider: '#d7e0e6',
    bodyText: '#293339',
    bodyTextChecked: '#000000',
    bodySubtext: '#455560',
    bodyDivider: '#d7e0e6',
    disabledBodyText: '#80939f',
    disabledBodySubtext: '#a9b4bb',
    focusBorder: '#455560',
    variantBorder: '#d7e0e6',
    variantBorderHovered: '#80939f',
    defaultStateBackground: '#f1f5f8',
    actionLink: '#293339',
    actionLinkHovered: '#131a1e',
    link: '#2270bf',
    linkHovered: '#123f6b',
    buttonBackground: '#ffffff',
    buttonBackgroundChecked: '#a9b4bb',
    buttonBackgroundHovered: '#ecf0f4',
    buttonBackgroundCheckedHovered: '#d7e0e6',
    buttonBackgroundPressed: '#d7e0e6',
    buttonBackgroundDisabled: '#ecf0f4',
    buttonBorder: '#8a8886',
    buttonText: '#293339',
    buttonTextHovered: '#131a1e',
    buttonTextChecked: '#131a1e',
    buttonTextCheckedHovered: '#000000',
    buttonTextPressed: '#131a1e',
    buttonTextDisabled: '#80939f',
    buttonBorderDisabled: '#ecf0f4',
    primaryButtonBackground: '#2270bf',
    primaryButtonBackgroundHovered: '#1c65ac',
    primaryButtonBackgroundPressed: '#185591',
    primaryButtonBackgroundDisabled: '#ecf0f4',
    primaryButtonBorder: 'transparent',
    primaryButtonText: '#ffffff',
    primaryButtonTextHovered: '#ffffff',
    primaryButtonTextPressed: '#ffffff',
    primaryButtonTextDisabled: '#b4b8bc',
    accentButtonBackground: '#569fae',
    accentButtonText: '#ffffff',
    inputBorder: '#455560',
    inputBorderHovered: '#293339',
    inputBackground: '#ffffff',
    inputBackgroundChecked: '#2270bf',
    inputBackgroundCheckedHovered: '#185591',
    inputForegroundChecked: '#ffffff',
    inputFocusBorderAlt: '#2270bf',
    smallInputBorder: '#455560',
    inputText: '#293339',
    inputTextHovered: '#131a1e',
    inputPlaceholderText: '#455560',
    disabledBackground: '#ecf0f4',
    disabledText: '#80939f',
    disabledSubtext: '#b4b8bc',
    listBackground: '#ffffff',
    listText: '#293339',
    listItemBackgroundHovered: '#ecf0f4',
    listItemBackgroundChecked: '#d7e0e6',
    listItemBackgroundCheckedHovered: '#c7d1d8',
    listHeaderBackgroundHovered: '#ecf0f4',
    listHeaderBackgroundPressed: '#d7e0e6',
    menuBackground: '#ffffff',
    menuDivider: '#a9b4bb',
    menuIcon: '#2270bf',
    menuHeader: '#2270bf',
    menuItemBackgroundHovered: '#ecf0f4',
    menuItemBackgroundPressed: '#d7e0e6',
    menuItemText: '#293339',
    menuItemTextHovered: '#131a1e',
    errorText: '#a4262c',
    errorBackground: '#FDE7E9',
    blockingBackground: '#FDE7E9',
    warningBackground: '#FFF4CE',
    successBackground: '#DFF6DD',
    warningHighlight: '#ffb900',
    warningText: '#323130',
    listTextColor: '#293339',
    menuItemBackgroundChecked: '#d7e0e6'
  },
  isInverted: false,
  disableGlobalClassNames: false
};
