define([], function () {
  return {
    AddCircleMaskFieldLabel: 'Add circle mask to profile image',
    BusinessPhonesFormLabel: 'Business phone',
    CityFormLabel: 'City',
    CloseButton: 'Close',
    ContentGroupName: 'Content',
    CopyAsHtmlFieldLabel: 'Copy as HTML',
    CopyAsHtmlButton: 'Copy as HTML',
    CopySignatureButton: 'Copy signature',
    CopySignatureSuccessButton: 'Copied!',
    CountryFormLabel: 'Country',
    CustomPropertyCollectionLabel: 'Custom properties',
    CustomPropertyManageButton: 'Manage custom properties',
    DepartmentFormLabel: 'Department',
    DisplayNameFormLabel: 'Name',
    DownloadAsHtmlButton: 'Download HTML',
    DownloadAsHtmlFieldLabel: 'Enable download HTML',
    EditValuesButton: 'Edit signature',
    EnableEditingFieldLabel: 'Enable editing',
    ErrorMessage: 'Sorry, an error occurred. Try refreshing the page.',
    ForceLowercaseEmailsFieldLabel: 'Force lowercase emails',
    GivenNameFormLabel: 'First name',
    HtmlTemplateFieldLabel: 'HTML (Mustache) template',
    ImageSizeFieldLabel: 'Image size (px)',
    JobTitleFormLabel: 'Job title',
    KeyCollectionLabel: 'Key (Mustache variable)',
    LabelCollectionLabel: 'Label',
    MailFormLabel: 'Email',
    MobilePhoneFormLabel: 'Mobile number',
    OfficeLocationFormLabel: 'Office location',
    PostalCodeFormLabel: 'ZIP or postal code',
    PropertyPaneDescription:
      'Displays a template replaced with profile properties. HTML templates use Mustache to render the email signature. Profile properties from Graph include:\n{{businessPhones}}, {{city}}, {{country}}, {{department}}, {{displayName}}, {{givenName}}, {{jobTitle}}, {{mail}}, {{mobilePhone}}, {{postalCode}}, {{preferredLanguage}}, {{state}}, {{streetAddress}}, {{surname}}.',
    StateFormLabel: 'State or province',
    StreetAddressFormLabel: 'Street address',
    SurnameFormLabel: 'Last name',
    UserEditableCollectionLabel: 'User editable',
    ValueCollectionLabel: 'Value',
    WebPartTitleFieldLabel: 'Web part title'
  };
});
