define([], function () {
  return {
    AddCircleMaskFieldLabel: 'Agregar máscara circular a la imagen de perfil',
    BusinessPhonesFormLabel: 'Teléfono de trabajo',
    CityFormLabel: 'Ciudad',
    CloseButton: 'Cerrar',
    ContentGroupName: 'Contenido',
    CopyAsHtmlFieldLabel: 'Copiar como HTML',
    CopyAsHtmlButton: 'Copiar como HTML',
    CopySignatureButton: 'Copiar firma',
    CopySignatureSuccessButton: '¡Copiado!',
    CountryFormLabel: 'País',
    CustomPropertyCollectionLabel: 'Propiedades personalizadas',
    CustomPropertyManageButton: 'Gestionar propiedades personalizadas',
    DepartmentFormLabel: 'Departamento',
    DisplayNameFormLabel: 'Nombre',
    DownloadAsHtmlButton: 'Descarga HTML',
    DownloadAsHtmlFieldLabel: 'Habilitar descarga HTML',
    EditValuesButton: 'Editar firma',
    EnableEditingFieldLabel: 'Habilitar edición',
    ErrorMessage: 'Lo sentimos, ocurrió un error. Intente actualizar la página.',
    ForceLowercaseEmailsFieldLabel: 'Forzar correos electrónicos en minúsculas',
    GivenNameFormLabel: 'Nombre de pila',
    HtmlTemplateFieldLabel: 'Plantilla HTML (Mustache)',
    ImageSizeFieldLabel: 'Tamaño de la imagen (px)',
    JobTitleFormLabel: 'Título del trabajo',
    KeyCollectionLabel: 'Clave (variable Mustache)',
    LabelCollectionLabel: 'Etiqueta',
    MailFormLabel: 'Correo electrónico',
    MobilePhoneFormLabel: 'Número de móvil',
    OfficeLocationFormLabel: 'Ubicación de la oficina',
    PostalCodeFormLabel: 'Código postal',
    PropertyPaneDescription:
      'Muestra una plantilla reemplazada con propiedades de perfil. Las plantillas HTML usan Mustache para renderizar la firma de correo electrónico. Las propiedades de perfil de Graph incluyen:\n{{businessPhones}}, {{city}}, {{country}}, {{department}}, {{displayName}}, {{givenName}}, {{jobTitle}}, {{mail}}, {{mobilePhone}}, {{postalCode}}, {{preferredLanguage}}, {{state}}, {{streetAddress}}, {{surname}}.',
    StateFormLabel: 'Estado o provincia',
    StreetAddressFormLabel: 'Dirección',
    SurnameFormLabel: 'Apellido',
    UserEditableCollectionLabel: 'Editable por el usuario',
    ValueCollectionLabel: 'Valor',
    WebPartTitleFieldLabel: 'Título de la parte web'
  };
});
