define([], function () {
  return {
    AddCircleMaskFieldLabel: "Ajouter un masque circulaire à l'image de profil",
    BusinessPhonesFormLabel: 'Téléphone professionnel',
    CityFormLabel: 'Ville',
    CloseButton: 'Fermer',
    ContentGroupName: 'Contenu',
    CopyAsHtmlFieldLabel: 'Copier en HTML',
    CopyAsHtmlButton: 'Copier en HTML',
    CopySignatureButton: 'Copier la signature',
    CopySignatureSuccessButton: 'Copié!',
    CountryFormLabel: 'Pays',
    CustomPropertyCollectionLabel: 'Propriétés personnalisées',
    CustomPropertyManageButton: 'Gérer les propriétés personnalisées',
    DepartmentFormLabel: 'Département',
    DisplayNameFormLabel: 'Nom',
    DownloadAsHtmlButton: 'Téléchargement HTML',
    DownloadAsHtmlFieldLabel: 'Activer le téléchargement HTML',
    EditValuesButton: 'Modifier la signature',
    EnableEditingFieldLabel: 'Activer la modification',
    ErrorMessage: "Désolé, une erreur s'est produite. Essayez de rafraîchir la page.",
    ForceLowercaseEmailsFieldLabel: 'Forcer les emails en minuscules',
    GivenNameFormLabel: 'Prénom',
    HtmlTemplateFieldLabel: 'Modèle HTML (Mustache)',
    ImageSizeFieldLabel: "Taille de l'image (px)",
    JobTitleFormLabel: 'Titre du poste',
    KeyCollectionLabel: 'Clé (variable Mustache)',
    LabelCollectionLabel: 'Étiquette',
    MailFormLabel: 'Courriel',
    MobilePhoneFormLabel: 'Numéro de mobile',
    OfficeLocationFormLabel: 'Emplacement du bureau',
    PostalCodeFormLabel: 'Code postal',
    PropertyPaneDescription:
      'Affiche un modèle remplacé par des propriétés de profil. Les modèles HTML utilisent Mustache pour rendre la signature de courriel. Les propriétés de profil de Graph incluent :\n{{businessPhones}}, {{city}}, {{country}}, {{department}}, {{displayName}}, {{givenName}}, {{jobTitle}}, {{mail}}, {{mobilePhone}}, {{postalCode}}, {{preferredLanguage}}, {{state}}, {{streetAddress}}, {{surname}}.',
    StateFormLabel: 'État ou province',
    StreetAddressFormLabel: 'Adresse',
    SurnameFormLabel: 'Nom de famille',
    UserEditableCollectionLabel: "Modifiable par l'utilisateur",
    ValueCollectionLabel: 'Valeur',
    WebPartTitleFieldLabel: 'Titre de la partie Web'
  };
});
